### ISSUE TITLE
Can't search board with custom fields

### ISSUE THREAD

**Issue by JhonatanPereira** [bhushankumarl/trello-node-api#12]
I can't get Trello.board.search(boardId, fields) to work. It seens to be ignoring the fields param. Am I forgetting something?
#6

**Comment by bhushankumarl** [comment]
@JhonatanPereira 
What exactly error are you facing?
Can you also place the code snippet here that you are using?

**Comment by JhonatanPereira** [comment]
Sure!
The problem is that it appears to be ignoring the fields parameter. It returns just the default board fields, in this case, ignoring the checklists or anything else I put there.
`  var fields = {
      checklists: 'all'
    }
    let board = await Trello.board.search(board_id, board_fields)`

**Comment by bhushankumarl** [comment]
@JhonatanPereira 
What exactly error are you facing?

**Comment by bhushankumarl** [comment]
@JhonatanPereira 
Closing this issue as it's working perfectly.
