### ISSUE TITLE
Get Lists from board Id

### ISSUE THREAD

**Issue by devabluestudios** [bhushankumarl/trello-node-api#13]
Hey There,

Just wondering how would I get the lists from a board id with this package?
Its available on the trello api but i can't see where it is on this package

Thanks

**Comment by asalvadore** [comment]
same issue here. It doesn't seem to be available ? Would it be as easy as adding it to the `TrelloResource` ?

**Comment by bhushankumarl** [comment]
@devabluestudios @asalvadore 
Fixed in https://github.com/bhushankumarl/trello-node-api/releases/tag/v0.0.9
