### ISSUE TITLE
How would I add Query Params to Trello.member.searchBoards

### ISSUE THREAD

**Issue by dmastag** [bhushankumarl/trello-node-api#14]
I am in need to know the Organization also of the Boards that I belong to.

In the [API Reference](https://developers.trello.com/reference#membersidboards) you can put in additional fields like below and just put in true for organization.

![image](https://user-images.githubusercontent.com/5745805/63639236-21d06400-c6bb-11e9-8ce3-128fd3ac627f.png)

**Comment by bhushankumarl** [comment]
@dmastag Fixed in https://github.com/bhushankumarl/trello-node-api/releases/tag/v0.0.8
