### ISSUE TITLE
[Feature Request] Custom Fields

### ISSUE THREAD

**Issue by dmastag** [bhushankumarl/trello-node-api#15]
Implementation of Custom Fields into this already awesome library

[Custom Fields](https://developers.trello.com/reference#custom-fields)

**Comment by dmastag** [comment]
Pull Request #18 is a WIP for this

**Comment by particlep** [comment]
This would be a great addition. Any update?

**Comment by bhushankumarl** [comment]
@particlep  @dmastag Added in https://github.com/bhushankumarl/trello-node-api/releases/tag/v0.0.8
