### ISSUE TITLE
New requestData is not added to path

### ISSUE THREAD

**Issue by dmastag** [bhushankumarl/trello-node-api#16]
I had difficulties just as #6 and #12 and as I reviwed the lib I was wondering why the below requestData is not added to the path.

https://github.com/bhushankumarl/trello-node-api/blob/0c8ef0a501d115c9d33d3265e38ec5c81c5f1cc5/lib/TrelloResource.js#L260

**Comment by bhushankumarl** [comment]
@dmastag Fixed in https://github.com/bhushankumarl/trello-node-api/releases/tag/v0.0.8
