### ISSUE TITLE
Can I alter query params on a query?

### ISSUE THREAD

**Issue by jpsear** [bhushankumarl/trello-node-api#6]
Hey,

Nice library :)

The official Trello boards API page shows all the query params that can be passed to control things like the amount of data that is returned: https://developers.trello.com/v1.0/reference#boardsboardid-1

In particular, the `fields` property. Can I achieve this with this lib?

**Comment by bhushankumarl** [comment]
@jpsear 
Can you put your request sample here?

**Comment by bhushankumarl** [comment]
@jpsear 
Thank you for the quick reply. Can you also post function that you are using from this library?

**Comment by jpsear** [comment]
I guess I wouldn't know which to use. It would possibly be `trello.board.search(boardId)`

**Comment by bhushankumarl** [comment]
@jpsear 
That is already supported, here is the example :

```
    var boardId = 'BOARD_ID';
    var fields = {
        actions: 'all'
    };
    Trello.board.search(boardId, fields).then(function (response) {
        console.log('response ', response);
    }).catch(function (error) {
        console.log('error', error);
    });
```

```
    var boardId = 'BOARD_ID';
    var field = 'shortUrl';
    Trello.board.searchField(boardId, field).then(function (response) {
        console.log('response ', response);
    }).catch(function (error) {
        console.log('error', error);
    });
```

**Comment by JhonatanPereira** [comment]
I can't get `Trello.board.search(boardId, fields)` to work. It seens to be ignoring the `fields` param. Am I forgetting something?
