### ISSUE TITLE
TrelloConnectionError

### ISSUE THREAD

**Issue by jpsear** [bhushankumarl/trello-node-api#7]
I'm getting this error frequently — What does it actually mean?

```
{ type: 'TrelloConnectionError',
W20181029-12:47:32.780(0)? (STDERR)   message: 'An error occurred with our connection to Trello',
W20181029-12:47:32.780(0)? (STDERR)   statusCode: undefined } { message: 'An error occurred with our connection to Trello',
W20181029-12:47:32.780(0)? (STDERR)   stack: 'Error: An error occurred with our connection to Trello\n    (No stack trace)}
```

**Comment by jpsear** [comment]
It's worth noting that it's happening when I `promise.all` a big batch of requests (around 30)

**Comment by bhushankumarl** [comment]
@jpsear 
Can you please put your sample code here.

**Comment by jpsear** [comment]
Sure. I don't think it's a code issue, as I do get responses from some of the requests. Anyway, I'll post what I'm doing, to give you some context...

```js
import TrelloApi from 'trello-node-api'

const getBoardById = async (trello, boardId) => {
  try {
    const board = await trello.board.search(boardId)
    return board
  } catch (error) {
    console.log('[trello: getBoardById]', error)
  }
}

const getAllBoards = async (trello, boardIds) => {
  const boardPromises = boardIds.map(id => getBoardById(trello, id))
  return Promise.all(boardPromises)
}

const trello = new TrelloApi(clientId, accessToken)
const boardIds = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] // Just an example. I'm actually pulling these from the member.

  try {
   const boards = await getAllBoards(trello, boardIds)
   return boards
  } catch (error) {
    console.error('[trello]', error)
  }
```

**Comment by bhushankumarl** [comment]
@jpsear 
Please follow to this example :
```
    const promises = [];

    const boardIds = ['BOARD_ID_1','BOARD_ID_2'];
    const Trello = new TrelloApi(clientId, accessToken)
    boardIds.forEach((boardId) => {
        promises.push(Trello.board.search(boardId));
    });

    try {
        const boards = await Promise.all(promises);
        console.log('boards ', boards.length);
    } catch (error) {
        console.error('[trello]', error);
    }
```

**Comment by jpsear** [comment]
That's a different way of writing what I had (mine is written like that because it's application code, so it needs to be re-usable). 

Have you tried fetching 30 boards with a promise.all — you might get the same error as me.

FWIW, I also found out that Trello has an API to return all boards + their info with one call, so this is not needed. It's part of the members endpoint: `/members/{id}/boards`. So I'm going to use that.

**Comment by bhushankumarl** [comment]
@jpsear I did check for about 50 boards. It works like a charm.

However, A solution for your code block :

import TrelloApi from 'trello-node-api'

// async removed from here
const getBoardById = (trello, boardId) => {
  try {
  // await removed from here
    const board = trello.board.search(boardId)
    return board
  } catch (error) {
    console.log('[trello: getBoardById]', error)
  }
}

const getAllBoards = async (trello, boardIds) => {
  const boardPromises = boardIds.map(id => getBoardById(trello, id))
  return Promise.all(boardPromises)
}

const trello = new TrelloApi(clientId, accessToken)
const boardIds = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] // Just an example. I'm actually pulling these from the member.

try {
  const boards = await getAllBoards(trello, boardIds)
  return boards
} catch (error) {
  console.error('[trello]', error)
}

**Comment by jpsear** [comment]
Ah that's a great explanation. Cheers for taking the time! 👍
